### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by jonasbark** [arthur-ver/analog-nfts#1]
Hi there!

Upon trying to login on Ethereum mainnet I'm getting redirected to:
```
https://analog-nfts-kspn740vm-arthur-ver.vercel.app/auth/error?error=Cannot%20read%20property%20%27id%27%20of%20null
```

The content of the redirected page reads as:
```
Non existant user
```

And these are the requests:
![image](https://user-images.githubusercontent.com/1151304/117191405-ce477080-ade0-11eb-82b9-8c8b49d77c40.png)

Anything I'm doing wrong? Can I provide more useful information?
Thanks :)

**Comment by arthur-ver** [comment]
Hi! This repository is currently not meant to be used as a template, as this project is currently still under development. However, if you're interested in contributing, please let me know and we could have a chat.

**Comment by jonasbark** [comment]
Sure, it's also not what I was trying to do! I just wanted to report an issue on https://analog-next.vercel.app/ itself - feel free to close it if it's too early for github issues :)

**Comment by arthur-ver** [comment]
Alright, gotcha! :)
